# Generated by Django 5.1.3 on 2024-11-14 05:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("duracion", models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nombres", models.CharField(max_length=50)),
                ("apellidoPaterno", models.CharField(max_length=50)),
                ("apellidoMaternos", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=128)),
                ("vigencia", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("creditos", models.PositiveSmallIntegerField()),
                ("semestre", models.PositiveSmallIntegerField(default=1)),
                (
                    "prerequisitos",
                    models.ManyToManyField(blank=True, to="Academica.curso"),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Academica.profesor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "cc",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nombres", models.CharField(max_length=50)),
                ("apellidoPaterno", models.CharField(max_length=50)),
                ("apellidoMaternos", models.CharField(max_length=50)),
                ("fechaNacimiento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        default="F",
                        max_length=1,
                    ),
                ),
                ("vigencia", models.BooleanField(default=True)),
                ("password", models.CharField(default="", max_length=128)),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Academica.carrera",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadoCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EC", "En Curso"),
                            ("SC", "Sin Cursar"),
                            ("AP", "Aprobada"),
                        ],
                        default="SC",
                        max_length=2,
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Academica.curso",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Academica.estudiante",
                    ),
                ),
            ],
            options={
                "unique_together": {("estudiante", "curso")},
            },
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fechaMatricula", models.DateField(auto_now_add=True)),
                (
                    "N1",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "N2",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "N3",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "examen_final",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Academica.curso",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Academica.estudiante",
                    ),
                ),
            ],
            options={
                "unique_together": {("estudiante", "curso")},
            },
        ),
        migrations.CreateModel(
            name="Pensum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semestre", models.PositiveSmallIntegerField()),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Academica.carrera",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Academica.curso",
                    ),
                ),
            ],
            options={
                "unique_together": {("carrera", "curso")},
            },
        ),
    ]
